/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.gradle.api.Project;

import java.io.File;
import java.util.Collections;

import org.example.artifacttranforms.AarToJarTransform;
import org.example.extensions.JavaCompileExtension;
import org.example.tasks.CompileTask;
import org.gradle.api.Plugin;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Copy;

import org.gradle.api.artifacts.Configuration;
import org.gradle.api.artifacts.ConfigurationContainer;
import org.gradle.api.artifacts.dsl.Dependencies;
import org.gradle.api.artifacts.dsl.DependencyCollector;
import org.gradle.api.attributes.Attribute;
import org.gradle.api.attributes.AttributeCompatibilityRule;
import org.gradle.api.attributes.AttributeDisambiguationRule;
import org.gradle.api.attributes.CompatibilityCheckDetails;
import org.gradle.api.attributes.MultipleCandidatesDetails;

/**
 * A simple 'hello world' plugin.
 */

interface GreetingPluginExtension {
    Property<String> getMessage();
}

interface ExampleDependencies extends Dependencies {
    DependencyCollector getImplementation();
}

abstract class CustomDisambiguationRule implements AttributeDisambiguationRule<String> {
    @Override
    public void execute(MultipleCandidatesDetails<String> details) {
        System.out.println("===============================");
        System.out.println(details.getConsumerValue());
        System.out.println(details.getCandidateValues().size());
        // if (details.getConsumerValue() != null && details.get() != null) {
        //     if (context.getProducerValue().equals("standard-jvm")) {
        //         context.closestMatch("standard-jvm");
        //     }
        // }
    }
}

class JvmEnvironmentCompatibilityRule implements AttributeCompatibilityRule<String> {
    @Override
    public void execute(CompatibilityCheckDetails<String> details) {
        System.out.println("JvmEnvironmentCompatibilityRule: " + details.getConsumerValue() + " " + details.getProducerValue());
        if(
            details.getConsumerValue().equals("android")
            && 
            details.getProducerValue().equals("standard-jvm")
        ){
            details.compatible();
        }
    }
}
class KotlinPlatformTypeCompatibilityRule implements AttributeCompatibilityRule<String> {
    @Override
    public void execute(CompatibilityCheckDetails<String> details) {
        System.out.println("KotlinPlatformTypeCompatibilityRule: " + details.getConsumerValue() + " " + details.getProducerValue());
        if(
            details.getConsumerValue().equals("androidJvm")
            && 
            details.getProducerValue().equals("jvm")
        ){
            details.compatible();
        }
    }
}

public class MypluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        System.out.println(">>>>>>> MyPlugin Configuration");

        // project.getDependencies().attributesSchema(attSchema -> {
        //     attSchema.attribute(
        //         Attribute.of("org.gradle.jvm.environment", String.class),
        //         (attMatchingStrategy) -> {
        //             attMatchingStrategy.getDisambiguationRules().add(CustomDisambiguationRule.class);
        //         }
        //     );
        // });

        project.getDependencies().getAttributesSchema().attribute(
            Attribute.of("org.gradle.jvm.environment", String.class)
        )
        .getCompatibilityRules()
        .add(JvmEnvironmentCompatibilityRule.class);
        project.getDependencies().getAttributesSchema().attribute(
            Attribute.of("org.jetbrains.kotlin.platform.type", String.class)
        )
        .getCompatibilityRules()
        .add(KotlinPlatformTypeCompatibilityRule.class);

        ConfigurationContainer configureContainer = project.getConfigurations();
        Configuration config = configureContainer.create("myConfig");
        config.setCanBeDeclared(true);
        config.setCanBeResolved(false);
        config.setCanBeConsumed(false);

        Configuration myConfig2 = configureContainer.create("myConfig2");
        myConfig2.extendsFrom(config);
        myConfig2.setCanBeDeclared(true);
        myConfig2.setCanBeResolved(true);
        myConfig2.setCanBeConsumed(false);

        // com.android.build.api.attributes.BuildTypeAttr: release
        // org.gradle.usage: java-runtime
        // org.gradle.jvm.environment: android
        // com.android.build.api.attributes.AgpVersionAttr: 8.11.0
        // org.gradle.category: library
        // org.jetbrains.kotlin.platform.type: androidJvm

        // com.android.build.api.attributes.BuildTypeAttr: release
        // org.gradle.usage: java-api
        // org.gradle.jvm.environment: android
        // com.android.build.api.attributes.AgpVersionAttr: 8.11.0
        // org.gradle.category: library
        // org.jetbrains.kotlin.platform.type: androidJvm
        
        var myConfig2Atts = myConfig2.getAttributes();
        // myConfig2Atts.attribute(Attribute.of("artifactType", String.class), "jar");
        myConfig2Atts.attribute(Attribute.of("com.android.build.api.attributes.BuildTypeAttr", String.class), "release");
        myConfig2Atts.attribute(Attribute.of("org.gradle.usage", String.class), "java-api");
        myConfig2Atts.attribute(Attribute.of("org.gradle.jvm.environment", String.class), "android");
        myConfig2Atts.attribute(Attribute.of("com.android.build.api.attributes.AgpVersionAttr", String.class), "8.11.0");
        myConfig2Atts.attribute(Attribute.of("org.gradle.category", String.class), "library");
        myConfig2Atts.attribute(Attribute.of("org.jetbrains.kotlin.platform.type", String.class), "androidJvm");

        // Register artifact transform
        var dependencyHandler  = project.getDependencies();
        dependencyHandler.registerTransform(
            AarToJarTransform.class,
            transformSpec -> {
                transformSpec.getFrom()
                    .attribute(Attribute.of("artifactType", String.class), "aar");
                transformSpec.getTo()
                    .attribute(Attribute.of("artifactType", String.class), "jar");
            }
        );

        // Create a extensions
        var extensionContainer = project.getExtensions();
        var javaCompileExtension = extensionContainer.create("javacompile", JavaCompileExtension.class);

        // Register a task
        var taskContainer = project.getTasks();
        taskContainer.register("vinh", task -> {
            myConfig2.getIncoming().artifactView(view -> {
                view.getAttributes().attribute(Attribute.of("artifactType", String.class), "jar");
            })
            .getFiles()
            .forEach(f -> {
                System.out.println(f);
            });
        });
        taskContainer.register("greeting", task -> {
            task.doLast(s -> {
                // releaseCompileClasspath releaseRuntimeClasspath
                var releaseCompileClasspath = configureContainer.getByName("myConfig2");
                releaseCompileClasspath.setExtendsFrom(Collections.emptyList());
                releaseCompileClasspath.extendsFrom(config);
                var attributeContainer = releaseCompileClasspath.getAttributes();
                attributeContainer.keySet().forEach(key -> {
                    System.out.println(key + ": " + attributeContainer.getAttribute(key));
                });

                System.out.println();
                // var result = releaseCompileClasspath.getIncoming().getResolutionResult();
                // var rootC = result.getRootComponent().get();
                // var rootV = result.getRootVariant().get();
                // var queue = new ArrayDeque<Tuple2<ResolvedComponentResult, ResolvedVariantResult>>();
                // queue.add(new Tuple2<ResolvedComponentResult, ResolvedVariantResult>(rootC, rootV));
                // while(!queue.isEmpty()){
                //     var entry = queue.removeFirst();
                //     var c = entry.getV1();
                //     var v = entry.getV2();
                //     System.out.println(c.getId());
                //     System.out.println(v.getDisplayName());
                //     c.getDependenciesForVariant(v).forEach(dependency -> {
                //         if (dependency instanceof UnresolvedDependencyResult a) {
                //             a.getFailure();
                //         }
                //         if (!(dependency instanceof ResolvedDependencyResult)) {
                //             throw new RuntimeException("Unknown dependency type: " + dependency);
                //         }
                //         var resolved = (ResolvedDependencyResult)dependency;
                //         if (!dependency.isConstraint()) {
                //             var toVariant = resolved.getResolvedVariant();
                //             queue.add(
                //                 new Tuple2<ResolvedComponentResult, ResolvedVariantResult>(resolved.getSelected(), toVariant));
                //             System.out.println("   " + toVariant.getDisplayName());
                //         }
                //     });
                // }

                System.out.println();
                System.out.println("releaseCompileClasspath.resolve()");
                releaseCompileClasspath.resolve().forEach(f -> {
                    System.out.println(f.getName());
                });
                System.out.println();
            });
        });

        final var TASK_GROUP = "MyTask";
        taskContainer.register("copylib", Copy.class, task -> {
            task.setGroup(TASK_GROUP);
            task.from(
                myConfig2.getIncoming().artifactView(view -> {
                    view.getAttributes().attribute(Attribute.of("artifactType", String.class), "jar");
                })
                .getFiles()
            );
            task.setDestinationDir(new File(project.getProjectDir(), "src/main/libs-tmp"));
        });
        taskContainer.register("compile", CompileTask.class, task -> {
            task.setGroup(TASK_GROUP);
            task.setSource(new File(project.getProjectDir(), "src/main/java"));
            task.getDestinationDirectory().set(new File(project.getProjectDir(), "build"));
            task.setSourceCompatibility(javaCompileExtension.getVersion().get().toString());
            task.setTargetCompatibility(javaCompileExtension.getVersion().get().toString());
            task.setClasspath(
                myConfig2.getIncoming().artifactView(view -> {
                    view.getAttributes().attribute(Attribute.of("artifactType", String.class), "jar");
                })
                .getFiles()
            );
        });
    }
}
